import 'dart:async';

import 'package:auto_route/auto_route.dart';
import 'package:dio/dio.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:island_ui_foundation/island_ui_foundation.dart';
import 'package:material_symbols_icons/symbols.dart';
import 'package:solar_network_foundation/solar_network_foundation.dart'
    as foundation;
import 'package:solwatt/flywheel/flywheel_page.dart';
import 'package:solwatt/network.dart';
import 'package:solwatt/ui/alert.dart';
import 'package:solwatt/ui/cloud_files.dart';
import 'package:solwatt/ui/page_scaffold.dart';
import 'package:solwatt/workspaces/workspace_actions.dart';
import 'package:solwatt/workspaces/workspace_management.dart';

/// Workspace detail console: identity, storage and members (Overview),
/// workspace-scoped mail administration (Mail), and Flywheel app usage.
///
/// Reached from the workspace list by slug. The route itself is generated by
/// auto_route from [WorkspaceDetailPage] (`WorkspaceDetailRoute`).
@RoutePage()
class WorkspaceDetailPage extends ConsumerStatefulWidget {
  const WorkspaceDetailPage({super.key, @PathParam('slug') required this.slug});

  final String slug;

  @override
  ConsumerState<WorkspaceDetailPage> createState() => _WorkspaceDetailPageState();
}

class _WorkspaceDetailPageState extends ConsumerState<WorkspaceDetailPage> {
  void _refresh() {
    ref.invalidate(workspacesProvider);
    ref.invalidate(selectedWorkspaceProvider);
  }

  @override
  Widget build(BuildContext context) {
    final workspaces = ref.watch(workspacesProvider);
    final workspace = _workspaceBySlug(
      workspaces.value ?? const <Workspace>[],
      widget.slug,
    );

    return DefaultTabController(
      length: 3,
      child: PageScaffold(
        title: workspace?.name ?? 'workspace'.tr(),
        subtitle: workspace == null ? null : '@${workspace.slug}',
        action: IconButton.filledTonal(
          tooltip: 'refresh'.tr(),
          onPressed: _refresh,
          icon: const Icon(Symbols.refresh),
        ),
        bottom: TabBar(
          tabs: [
            Tab(text: 'workspaceOverview'.tr()),
            Tab(text: 'mail'.tr()),
            Tab(text: 'flywheel'.tr()),
          ],
        ),
        child: workspaces.when(
          loading: () => const PageLoading(),
          error: (error, _) => PageError(
            message: 'workspaceLoadError'.tr(),
            onRetry: _refresh,
          ),
          data: (items) {
            final value = _workspaceBySlug(items, widget.slug);
            if (value == null) {
              return EmptyState(
                icon: Symbols.workspaces,
                title: 'workspaceNotFound'.tr(),
              );
            }
            return TabBarView(
              children: [
                _OverviewTab(workspace: value),
                _MailTab(workspace: value),
                _FlywheelTab(workspace: value),
              ],
            );
          },
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Overview
// ---------------------------------------------------------------------------

class _OverviewTab extends ConsumerStatefulWidget {
  const _OverviewTab({required this.workspace});

  final Workspace workspace;

  @override
  ConsumerState<_OverviewTab> createState() => _OverviewTabState();
}

class _OverviewTabState extends ConsumerState<_OverviewTab> {
  late Future<List<WorkspaceMember>> _members;

  @override
  void initState() {
    super.initState();
    _reloadMembers();
  }

  void _reloadMembers() {
    _members = ref
        .read(wattEngineClientProvider)
        .listWorkspaceMembers(widget.workspace.slug);
  }

  Future<void> _activate() => activateWorkspaceAction(ref, widget.workspace);

  @override
  Widget build(BuildContext context) {
    final workspace = widget.workspace;
    final isActive =
        ref.watch(selectedWorkspaceProvider).value?.id == workspace.id;
    final quota = ref.watch(workspaceStorageQuotaProvider(workspace.slug));

    return ListView(
      padding: const EdgeInsets.only(top: 16, bottom: 32),
      children: [
        _Panel(
          padding: EdgeInsets.zero,
          child: _identity(workspace, isActive),
        ),
        const SizedBox(height: 12),
        _Panel(child: _actionRow(workspace)),
        const SizedBox(height: 12),
        _Panel(child: _storageSection(workspace, quota)),
        const SizedBox(height: 12),
        _TitledPanel(
          title: 'members'.tr(),
          trailing: FilledButton.tonal(
            onPressed: () => showWorkspaceMembers(context, workspace),
            child: Text('manageMembers'.tr()),
          ),
          child: _membersSection(workspace),
        ),
      ],
    );
  }

  Widget _identity(Workspace workspace, bool isActive) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final background = workspace.background;
    final description = workspace.description?.trim();
    final expiresAt = workspace.planExpiresAt;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (background != null)
          ClipRRect(
            borderRadius: const BorderRadius.vertical(
              top: Radius.circular(12),
            ),
            child: SizedBox(
              height: 140,
              width: double.infinity,
              child: Image(
                image: foundation.cloudFileImageProvider(
                  serverUrl: kSolarNetworkApiBase,
                  id: background.id,
                  storageUrl: background.storageUrl,
                  workspaceId: workspace.id,
                ),
                fit: BoxFit.cover,
                errorBuilder: (_, _, _) => const SizedBox.shrink(),
              ),
            ),
          ),
        Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  CloudFileAvatar(
                    file: workspace.picture,
                    workspaceId: workspace.id,
                    fallbackIcon: Symbols.workspaces,
                    size: 64,
                    assumeImage: true,
                    borderRadius: workspace.isIndividual
                        ? BorderRadius.circular(999)
                        : null,
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          workspace.name,
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: text.titleLarge?.copyWith(
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          '@${workspace.slug}',
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: text.bodyMedium?.copyWith(
                            color: scheme.onSurfaceVariant,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              if (description != null && description.isNotEmpty) ...[
                const SizedBox(height: 14),
                Text(
                  description,
                  style: text.bodyMedium?.copyWith(
                    color: scheme.onSurfaceVariant,
                    height: 1.4,
                  ),
                ),
              ],
              const SizedBox(height: 14),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  StatusChip(
                    label: workspace.isIndividual
                        ? 'personalWorkspace'.tr()
                        : 'organizationWorkspace'.tr(),
                    icon: workspace.isIndividual
                        ? Symbols.person
                        : Symbols.corporate_fare,
                    tone: StatusChipTone.primary,
                  ),
                  StatusChip(
                    label: workspace.planName,
                    icon: Symbols.workspace_premium,
                    tone: StatusChipTone.secondary,
                  ),
                  if (workspace.isBundled)
                    StatusChip(
                      label: 'bundledPro'.tr(),
                      icon: Symbols.card_giftcard,
                      tone: StatusChipTone.tertiary,
                    ),
                  if (expiresAt != null)
                    StatusChip(
                      label: 'expires'.tr(
                        namedArgs: {'date': _formatDate(expiresAt)},
                      ),
                      icon: Symbols.schedule,
                      tone: StatusChipTone.neutral,
                    ),
                ],
              ),
              const SizedBox(height: 16),
              if (isActive)
                StatusChip(
                  label: 'activeWorkspace'.tr(),
                  icon: Symbols.check_circle,
                  tone: StatusChipTone.primary,
                )
              else
                Align(
                  alignment: Alignment.centerLeft,
                  child: FilledButton.tonalIcon(
                    onPressed: _activate,
                    icon: const Icon(Symbols.check_circle),
                    label: Text('workspaceSetActive'.tr()),
                  ),
                ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _actionRow(Workspace workspace) => Wrap(
    spacing: 8,
    runSpacing: 8,
    children: [
      FilledButton.tonalIcon(
        onPressed: () => editWorkspaceAction(context, ref, workspace),
        icon: const Icon(Symbols.edit),
        label: Text('edit'.tr()),
      ),
      FilledButton.tonalIcon(
        onPressed: () => showWorkspaceMembers(context, workspace),
        icon: const Icon(Symbols.group),
        label: Text('members'.tr()),
      ),
      FilledButton.tonalIcon(
        onPressed: () => showWorkspaceQuota(context, ref, workspace),
        icon: const Icon(Symbols.workspace_premium),
        label: Text('planAndQuotas'.tr()),
      ),
    ],
  );

  Widget _storageSection(
    Workspace workspace,
    AsyncValue<WorkspaceStorageQuota?> quota,
  ) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Row(
          children: [
            Expanded(
              child: Text(
                'storageQuota'.tr(),
                style: text.titleMedium?.copyWith(fontWeight: FontWeight.w700),
              ),
            ),
          ],
        ),
        const SizedBox(height: 12),
        quota.when(
          loading: () => const Padding(
            padding: EdgeInsets.symmetric(vertical: 24),
            child: Center(child: CircularProgressIndicator()),
          ),
          error: (error, _) => _InlineError(
            message: 'errorLoadingQuota'.tr(),
            onRetry: () =>
                ref.invalidate(workspaceStorageQuotaProvider(workspace.slug)),
          ),
          data: (value) {
            if (value == null) {
              return _InlineError(
                message: 'errorLoadingQuota'.tr(),
                onRetry: () => ref.invalidate(
                  workspaceStorageQuotaProvider(workspace.slug),
                ),
              );
            }
            final hasTotal = value.totalBytes > 0;
            final ratio = hasTotal
                ? (value.usedBytes / value.totalBytes).clamp(0.0, 1.0)
                : 0.0;
            return Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'storageUsed'.tr(
                    namedArgs: {
                      'used': _formatBytes(value.usedBytes),
                      'total': _formatBytes(value.totalBytes),
                      'percent': (ratio * 100).toStringAsFixed(0),
                    },
                  ),
                ),
                if (hasTotal) ...[
                  const SizedBox(height: 8),
                  ClipRRect(
                    borderRadius: BorderRadius.circular(6),
                    child: LinearProgressIndicator(value: ratio, minHeight: 8),
                  ),
                ],
                const SizedBox(height: 8),
                Text(
                  'fileCount'.tr(
                    namedArgs: {'count': '${value.totalFileCount}'},
                  ),
                  style: text.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
                if (value.services.isNotEmpty) ...[
                  const SizedBox(height: 16),
                  Text(
                    'serviceUsage'.tr(),
                    style: text.titleSmall?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  for (final service in value.services)
                    Padding(
                      padding: const EdgeInsets.symmetric(vertical: 4),
                      child: Row(
                        children: [
                          Expanded(
                            child: Text(
                              service.displayName,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: const TextStyle(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                          const SizedBox(width: 12),
                          Text(
                            _formatBytes(service.usedBytes),
                            style: text.bodyMedium?.copyWith(
                              color: scheme.onSurfaceVariant,
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
                if (value.calculatedAt != null) ...[
                  const SizedBox(height: 12),
                  Text(
                    'quotaCalculatedAt'.tr(
                      args: [_formatDateTime(value.calculatedAt!)],
                    ),
                    style: text.bodySmall?.copyWith(
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ],
            );
          },
        ),
      ],
    );
  }

  Widget _membersSection(Workspace workspace) => FutureBuilder<List<WorkspaceMember>>(
    future: _members,
    builder: (context, snapshot) {
      if (snapshot.connectionState != ConnectionState.done) {
        return const Padding(
          padding: EdgeInsets.symmetric(vertical: 16),
          child: Center(child: CircularProgressIndicator()),
        );
      }
      if (snapshot.hasError) {
        return _InlineError(
          message: 'couldNotLoadMembers'.tr(),
          onRetry: () => setState(_reloadMembers),
        );
      }
      final members = snapshot.data ?? const <WorkspaceMember>[];
      if (members.isEmpty) {
        return _InlineEmpty(
          icon: Symbols.group,
          message: 'noMembers'.tr(),
          description: 'noWorkspaceMembersAvailable'.tr(),
        );
      }
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'workspaceMemberCount'.tr(
              namedArgs: {'count': '${members.length}'},
            ),
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
              color: Theme.of(context).colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 12),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              for (final member in members.take(5))
                _MemberChip(member: member),
              if (members.length > 5)
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8),
                  child: Text(
                    '+${members.length - 5}',
                    style: Theme.of(context).textTheme.labelLarge,
                  ),
                ),
            ],
          ),
        ],
      );
    },
  );
}

class _MemberChip extends StatelessWidget {
  const _MemberChip({required this.member});

  final WorkspaceMember member;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final avatarUrl = member.avatarUrl;
    return Container(
      padding: const EdgeInsets.fromLTRB(6, 6, 12, 6),
      decoration: BoxDecoration(
        color: scheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(999),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          CircleAvatar(
            radius: 16,
            backgroundColor: scheme.surfaceContainerHigh,
            backgroundImage: (avatarUrl != null && avatarUrl.isNotEmpty)
                ? NetworkImage(avatarUrl)
                : null,
            child: (avatarUrl == null || avatarUrl.isEmpty)
                ? Text(member.initial, style: text.labelLarge)
                : null,
          ),
          const SizedBox(width: 8),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              ConstrainedBox(
                constraints: const BoxConstraints(maxWidth: 140),
                child: Text(
                  member.label,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: text.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Text(
                _roleName(member.role),
                style: text.bodySmall?.copyWith(
                  color: scheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Mail
// ---------------------------------------------------------------------------

class _MailData {
  const _MailData({
    required this.mailHost,
    required this.mailboxes,
    required this.mailboxUsage,
    required this.domains,
    required this.credentials,
  });

  final String mailHost;
  final List<MailMailbox> mailboxes;
  final MailUsageSummary mailboxUsage;
  final List<MailCustomDomain> domains;
  final List<MailCredential> credentials;
}

typedef _MailboxDraft = ({String address, String? name, bool isDefault});

class _MailTab extends ConsumerStatefulWidget {
  const _MailTab({required this.workspace});

  final Workspace workspace;

  @override
  ConsumerState<_MailTab> createState() => _MailTabState();
}

class _MailTabState extends ConsumerState<_MailTab> {
  late Future<_MailData> _data;

  @override
  void initState() {
    super.initState();
    _data = _load();
  }

  Future<_MailData> _load() async {
    final client = ref.read(wattEngineClientProvider);
    final workspaceId = widget.workspace.id;
    var mailHost = '';
    try {
      mailHost = await client.getMailHost();
    } catch (_) {
      // A missing host only affects address rendering; the rest still loads.
    }
    final results = await Future.wait<Object>([
      client.listMailboxes(workspaceId: workspaceId),
      client.getWorkspaceMailboxUsage(workspaceId),
      client.listCustomDomains(workspaceId: workspaceId),
      client.listMailCredentials(),
    ]);
    return _MailData(
      mailHost: mailHost,
      mailboxes: results[0] as List<MailMailbox>,
      mailboxUsage: results[1] as MailUsageSummary,
      domains: results[2] as List<MailCustomDomain>,
      credentials: results[3] as List<MailCredential>,
    );
  }

  void _reload() {
    if (!mounted) return;
    setState(() => _data = _load());
  }

  Future<void> _createMailbox(_MailData data) async {
    final draft = await showModalBottomSheet<_MailboxDraft>(
      context: context,
      useRootNavigator: true,
      isScrollControlled: true,
      builder: (_) => _CreateMailboxSheet(mailHost: data.mailHost),
    );
    if (draft == null || !mounted) return;
    try {
      await ref
          .read(wattEngineClientProvider)
          .createMailbox(
            address: draft.address,
            workspaceId: widget.workspace.id,
            name: draft.name,
            isDefault: draft.isDefault,
          );
      _reload();
      showSnackBar('mailboxCreated'.tr());
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  Future<void> _openRouting(_MailData data, MailMailbox mailbox) async {
    await showModalBottomSheet<void>(
      context: context,
      useRootNavigator: true,
      isScrollControlled: true,
      builder: (_) => _MailboxRoutingSheet(
        mailbox: mailbox,
        workspaceId: widget.workspace.id,
        mailHost: data.mailHost,
        domains: data.domains,
        onChanged: _reload,
      ),
    );
  }

  Future<void> _createCredential(_MailData data) async {
    final created = await showModalBottomSheet<MailCredentialCreated>(
      context: context,
      useRootNavigator: true,
      isScrollControlled: true,
      builder: (_) => _CreateCredentialSheet(
        mailboxes: data.mailboxes,
        mailHost: data.mailHost,
      ),
    );
    if (created == null || !mounted) return;
    _reload();
    await _showSecret(created.secret);
  }

  Future<void> _showSecret(String secret) => showModalBottomSheet<void>(
    context: context,
    useRootNavigator: true,
    isScrollControlled: true,
    builder: (_) => _CredentialSecretSheet(secret: secret),
  );

  Future<void> _revokeCredential(MailCredential credential) async {
    final confirmed = await showConfirmAlert(
      'revokeCredentialConfirm'.tr(namedArgs: {'label': credential.label}),
      'revokeCredential'.tr(),
      icon: Symbols.key,
      isDanger: true,
      confirmLabel: 'revoke'.tr(),
    );
    if (!confirmed || !mounted) return;
    try {
      await ref
          .read(wattEngineClientProvider)
          .revokeMailCredential(credential.id);
      _reload();
      showSnackBar('credentialRevoked'.tr());
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  Future<void> _createDomain() async {
    final domain = await showModalBottomSheet<String>(
      context: context,
      useRootNavigator: true,
      isScrollControlled: true,
      builder: (_) => const _CreateDomainSheet(),
    );
    if (domain == null || domain.isEmpty || !mounted) return;
    try {
      await ref
          .read(wattEngineClientProvider)
          .createCustomDomain(workspaceId: widget.workspace.id, domain: domain);
      _reload();
      showSnackBar('workspaceDomainAdded'.tr());
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  Future<void> _refreshDomain(MailCustomDomain domain) async {
    try {
      await ref.read(wattEngineClientProvider).refreshCustomDomain(domain.id);
      _reload();
      showSnackBar('workspaceDomainRefreshed'.tr());
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  @override
  Widget build(BuildContext context) => FutureBuilder<_MailData>(
    future: _data,
    builder: (context, snapshot) {
      if (snapshot.connectionState != ConnectionState.done) {
        return const PageLoading();
      }
      if (snapshot.hasError) {
        return PageError(
          message: 'workspaceMailLoadError'.tr(),
          onRetry: _reload,
        );
      }
      final data = snapshot.data!;
      final mailboxIds = {for (final mailbox in data.mailboxes) mailbox.id};
      final credentials = data.credentials
          .where((credential) => mailboxIds.contains(credential.mailboxId))
          .toList(growable: false);

      return ListView(
        padding: const EdgeInsets.only(top: 16, bottom: 32),
        children: [
          _TitledPanel(
            title: 'workspaceMailboxes'.tr(),
            trailing: FilledButton.icon(
              onPressed: () => _createMailbox(data),
              icon: const Icon(Symbols.add),
              label: Text('newMailbox'.tr()),
            ),
            child: data.mailboxes.isEmpty
                ? _InlineEmpty(
                    icon: Symbols.mail,
                    message: 'workspaceMailboxesEmpty'.tr(),
                  )
                : Column(
                    children: [
                      for (var i = 0; i < data.mailboxes.length; i++) ...[
                        if (i > 0) const Divider(height: 1),
                        _MailboxTile(
                          mailbox: data.mailboxes[i],
                          mailHost: data.mailHost,
                          onTap: () =>
                              _openRouting(data, data.mailboxes[i]),
                        ),
                      ],
                    ],
                  ),
          ),
          const SizedBox(height: 12),
          _TitledPanel(
            title: 'workspaceMailboxUsage'.tr(),
            child: _UsageMeter(
              label: 'workspaceMailboxes'.tr(),
              used: data.mailboxUsage.used,
              limit: data.mailboxUsage.limit,
              remaining: data.mailboxUsage.remaining,
            ),
          ),
          const SizedBox(height: 12),
          _TitledPanel(
            title: 'mailCredentials'.tr(),
            trailing: FilledButton.tonalIcon(
              onPressed: data.mailboxes.isEmpty
                  ? null
                  : () => _createCredential(data),
              icon: const Icon(Symbols.key),
              label: Text('createCredential'.tr()),
            ),
            child: credentials.isEmpty
                ? _InlineEmpty(
                    icon: Symbols.key,
                    message: 'noCredentials'.tr(),
                    description: 'noCredentialsDescription'.tr(),
                  )
                : Column(
                    children: [
                      for (var i = 0; i < credentials.length; i++) ...[
                        if (i > 0) const Divider(height: 1),
                        _CredentialTile(
                          credential: credentials[i],
                          mailbox: _mailboxById(
                            data.mailboxes,
                            credentials[i].mailboxId,
                          ),
                          mailHost: data.mailHost,
                          onRevoke: () => _revokeCredential(credentials[i]),
                        ),
                      ],
                    ],
                  ),
          ),
          const SizedBox(height: 12),
          _TitledPanel(
            title: 'workspaceCustomDomains'.tr(),
            trailing: FilledButton.tonalIcon(
              onPressed: _createDomain,
              icon: const Icon(Symbols.add),
              label: Text('workspaceAddDomain'.tr()),
            ),
            child: data.domains.isEmpty
                ? _InlineEmpty(
                    icon: Symbols.dns,
                    message: 'workspaceDomainsEmpty'.tr(),
                  )
                : Column(
                    children: [
                      for (final domain in data.domains)
                        _DomainTile(
                          domain: domain,
                          onRefresh: () => _refreshDomain(domain),
                        ),
                    ],
                  ),
          ),
        ],
      );
    },
  );
}

MailMailbox? _mailboxById(List<MailMailbox> mailboxes, String id) {
  for (final mailbox in mailboxes) {
    if (mailbox.id == id) return mailbox;
  }
  return null;
}

class _MailboxTile extends StatelessWidget {
  const _MailboxTile({
    required this.mailbox,
    required this.mailHost,
    required this.onTap,
  });

  final MailMailbox mailbox;
  final String mailHost;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final name = mailbox.name?.trim();
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(8),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 10),
        child: Row(
          children: [
            const IconBadge(icon: Symbols.mail),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    mailbox.fullAddress(mailHost),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: text.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  if (name != null && name.isNotEmpty)
                    Text(
                      name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: text.bodySmall?.copyWith(
                        color: scheme.onSurfaceVariant,
                      ),
                    ),
                  const SizedBox(height: 6),
                  Wrap(
                    spacing: 6,
                    runSpacing: 4,
                    children: [
                      if (mailbox.isDefault)
                        StatusChip(
                          label: 'workspaceMailboxDefault'.tr(),
                          icon: Symbols.star,
                          tone: StatusChipTone.primary,
                        ),
                      StatusChip(
                        label: mailbox.isVerified
                            ? 'workspaceMailboxVerified'.tr()
                            : 'workspaceMailboxUnverified'.tr(),
                        icon: mailbox.isVerified
                            ? Symbols.verified
                            : Symbols.error,
                        tone: mailbox.isVerified
                            ? StatusChipTone.secondary
                            : StatusChipTone.error,
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Icon(Symbols.chevron_right, color: scheme.onSurfaceVariant),
          ],
        ),
      ),
    );
  }
}

class _CredentialTile extends StatelessWidget {
  const _CredentialTile({
    required this.credential,
    required this.mailbox,
    required this.mailHost,
    required this.onRevoke,
  });

  final MailCredential credential;
  final MailMailbox? mailbox;
  final String mailHost;
  final VoidCallback onRevoke;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final address = mailbox?.fullAddress(mailHost) ?? credential.mailboxId;
    final protocols = credential.protocols
        .map((protocol) => protocol.toUpperCase())
        .join(', ');
    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: const Icon(Symbols.key),
      title: Text(credential.label),
      subtitle: Text(
        protocols.isEmpty ? address : '$address · $protocols',
        maxLines: 1,
        overflow: TextOverflow.ellipsis,
      ),
      trailing: IconButton(
        tooltip: 'revoke'.tr(),
        onPressed: onRevoke,
        icon: Icon(Symbols.delete, color: scheme.error),
      ),
    );
  }
}

class _DomainTile extends StatelessWidget {
  const _DomainTile({required this.domain, required this.onRefresh});

  final MailCustomDomain domain;
  final VoidCallback onRefresh;

  @override
  Widget build(BuildContext context) {
    final text = Theme.of(context).textTheme;
    final stage = domain.stage?.trim();
    return ExpansionTile(
      tilePadding: EdgeInsets.zero,
      childrenPadding: const EdgeInsets.only(left: 8, right: 8, bottom: 12),
      title: Row(
        children: [
          Expanded(
            child: Text(
              domain.domain,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: text.titleSmall?.copyWith(fontWeight: FontWeight.w600),
            ),
          ),
          const SizedBox(width: 8),
          StatusChip(
            label: domain.isReady
                ? 'workspaceDomainReady'.tr()
                : 'workspaceDomainNeedsDns'.tr(),
            icon: domain.isReady ? Symbols.verified : Symbols.dns,
            tone: domain.isReady
                ? StatusChipTone.secondary
                : StatusChipTone.error,
          ),
        ],
      ),
      subtitle: (stage == null || stage.isEmpty) ? null : Text(stage),
      children: [
        if (domain.dnsRecords.isNotEmpty) ...[
          Align(
            alignment: Alignment.centerLeft,
            child: Text(
              'workspaceDnsRecords'.tr(),
              style: text.labelLarge,
            ),
          ),
          const SizedBox(height: 6),
          for (final record in domain.dnsRecords) _DnsRecordRow(record: record),
        ],
        Align(
          alignment: Alignment.centerLeft,
          child: TextButton.icon(
            onPressed: onRefresh,
            icon: const Icon(Symbols.refresh, size: 18),
            label: Text('workspaceRefreshVerification'.tr()),
          ),
        ),
      ],
    );
  }
}

class _DnsRecordRow extends StatelessWidget {
  const _DnsRecordRow({required this.record});

  final MailDnsRecord record;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              StatusChip(label: record.type, tone: StatusChipTone.neutral),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  record.name,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: text.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 4),
          SelectableText(record.value, style: text.bodySmall),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Mailbox routing sheet
// ---------------------------------------------------------------------------

class _RoutingData {
  const _RoutingData({
    required this.aliases,
    required this.forwardings,
    required this.quota,
    required this.sendUsage,
  });

  final List<MailAlias> aliases;
  final List<MailForwarding> forwardings;
  final MailboxQuota quota;
  final MailSendUsage sendUsage;
}

class _MailboxRoutingSheet extends ConsumerStatefulWidget {
  const _MailboxRoutingSheet({
    required this.mailbox,
    required this.workspaceId,
    required this.mailHost,
    required this.domains,
    required this.onChanged,
  });

  final MailMailbox mailbox;
  final String workspaceId;
  final String mailHost;
  final List<MailCustomDomain> domains;
  final VoidCallback onChanged;

  @override
  ConsumerState<_MailboxRoutingSheet> createState() =>
      _MailboxRoutingSheetState();
}

class _MailboxRoutingSheetState extends ConsumerState<_MailboxRoutingSheet> {
  final _aliasLocalPart = TextEditingController();
  final _aliasName = TextEditingController();
  final _forwardingDestination = TextEditingController();
  late Future<_RoutingData> _data;
  String? _customDomainId;
  String? _aliasId;
  bool _aliasSaving = false;
  bool _forwardingSaving = false;

  @override
  void initState() {
    super.initState();
    _data = _load();
  }

  @override
  void dispose() {
    _aliasLocalPart.dispose();
    _aliasName.dispose();
    _forwardingDestination.dispose();
    super.dispose();
  }

  Future<_RoutingData> _load() async {
    final client = ref.read(wattEngineClientProvider);
    final mailboxId = widget.mailbox.id;
    final results = await Future.wait<Object>([
      client.listMailboxAliases(mailboxId),
      client.listMailForwardings(mailboxId),
      client.getMailboxQuota(mailboxId),
      client.getWorkspaceSendUsage(widget.workspaceId),
    ]);
    return _RoutingData(
      aliases: results[0] as List<MailAlias>,
      forwardings: results[1] as List<MailForwarding>,
      quota: results[2] as MailboxQuota,
      sendUsage: results[3] as MailSendUsage,
    );
  }

  void _reload() {
    if (!mounted) return;
    setState(() => _data = _load());
    widget.onChanged();
  }

  Future<void> _createAlias() async {
    final domainId = _customDomainId;
    final localPart = _aliasLocalPart.text.trim().toLowerCase();
    if (domainId == null || localPart.isEmpty) return;
    setState(() => _aliasSaving = true);
    try {
      await ref
          .read(wattEngineClientProvider)
          .createMailboxAlias(
            mailboxId: widget.mailbox.id,
            customDomainId: domainId,
            localPart: localPart,
            name: _aliasName.text.trim(),
          );
      _aliasLocalPart.clear();
      _aliasName.clear();
      showSnackBar('aliasCreated'.tr());
      _reload();
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    } finally {
      if (mounted) setState(() => _aliasSaving = false);
    }
  }

  Future<void> _deleteAlias(MailAlias alias) async {
    final confirmed = await showConfirmAlert(
      'removeAliasConfirm'.tr(namedArgs: {'address': alias.address}),
      'removeAlias'.tr(),
      icon: Symbols.delete,
      isDanger: true,
      confirmLabel: 'remove'.tr(),
    );
    if (!confirmed) return;
    try {
      await ref
          .read(wattEngineClientProvider)
          .deleteMailboxAlias(widget.mailbox.id, alias.id);
      showSnackBar('aliasRemoved'.tr());
      _reload();
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  Future<void> _createForwarding() async {
    final aliasId = _aliasId;
    final destination = _forwardingDestination.text.trim().toLowerCase();
    if (aliasId == null || destination.isEmpty) return;
    setState(() => _forwardingSaving = true);
    try {
      await ref
          .read(wattEngineClientProvider)
          .createMailForwarding(
            mailboxId: widget.mailbox.id,
            aliasId: aliasId,
            destination: destination,
          );
      _forwardingDestination.clear();
      showSnackBar('forwardingCreated'.tr());
      _reload();
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    } finally {
      if (mounted) setState(() => _forwardingSaving = false);
    }
  }

  Future<void> _deleteForwarding(MailForwarding forwarding) async {
    final confirmed = await showConfirmAlert(
      'removeForwardingConfirm'.tr(
        namedArgs: {'destination': forwarding.destination},
      ),
      'removeForwarding'.tr(),
      icon: Symbols.delete,
      isDanger: true,
      confirmLabel: 'remove'.tr(),
    );
    if (!confirmed) return;
    try {
      await ref
          .read(wattEngineClientProvider)
          .deleteMailForwarding(widget.mailbox.id, forwarding.id);
      showSnackBar('forwardingRemoved'.tr());
      _reload();
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  @override
  Widget build(BuildContext context) {
    return SheetScaffold(
      titleText: widget.mailbox.fullAddress(widget.mailHost),
      heightFactor: 0.9,
      child: FutureBuilder<_RoutingData>(
        future: _data,
        builder: (context, snapshot) {
          if (snapshot.connectionState != ConnectionState.done) {
            return const PageLoading();
          }
          if (snapshot.hasError) {
            return PageError(
              message: 'workspaceMailboxDetailsLoadError'.tr(),
              onRetry: () => setState(() => _data = _load()),
            );
          }
          final data = snapshot.data!;
          return ListView(
            padding: const EdgeInsets.fromLTRB(20, 8, 20, 24),
            children: [
              _sheetSection('aliases', _aliasesBlock(data)),
              const SizedBox(height: 20),
              _sheetSection('forwarding', _forwardingBlock(data)),
              const SizedBox(height: 20),
              _sheetSection(
                'mailStorageQuota',
                _UsageMeter(
                  label: 'mailStorageQuota'.tr(),
                  used: data.quota.usedBytes,
                  limit: data.quota.limitBytes,
                  remaining: data.quota.remainingBytes,
                  isBytes: true,
                ),
              ),
              const SizedBox(height: 20),
              _sheetSection('workspaceSendUsage', _sendUsageBlock(data)),
            ],
          );
        },
      ),
    );
  }

  Widget _sheetSection(String titleKey, Widget child) {
    final text = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          titleKey.tr(),
          style: text.titleMedium?.copyWith(fontWeight: FontWeight.w700),
        ),
        const SizedBox(height: 8),
        child,
      ],
    );
  }

  Widget _aliasesBlock(_RoutingData data) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final verifiedDomains = widget.domains
        .where((domain) => domain.isReady)
        .toList(growable: false);
    final selectedDomainId =
        verifiedDomains.any((domain) => domain.id == _customDomainId)
        ? _customDomainId
        : null;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        if (verifiedDomains.isEmpty)
          Text(
            'noVerifiedDomains'.tr(),
            style: text.bodySmall?.copyWith(color: scheme.onSurfaceVariant),
          )
        else ...[
          DropdownButtonFormField<String>(
            initialValue: selectedDomainId,
            isExpanded: true,
            decoration: InputDecoration(
              isDense: true,
              labelText: 'customDomain'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
            items: [
              for (final domain in verifiedDomains)
                DropdownMenuItem(value: domain.id, child: Text(domain.domain)),
            ],
            onChanged: (value) => setState(() => _customDomainId = value),
          ),
          const SizedBox(height: 10),
          TextField(
            controller: _aliasLocalPart,
            keyboardType: TextInputType.emailAddress,
            decoration: InputDecoration(
              labelText: 'aliasLocalPart'.tr(),
              hintText: 'aliasLocalPartHint'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
          const SizedBox(height: 10),
          TextField(
            controller: _aliasName,
            decoration: InputDecoration(
              labelText: 'name'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
          const SizedBox(height: 10),
          Align(
            alignment: Alignment.centerLeft,
            child: FilledButton.tonalIcon(
              onPressed: (_aliasSaving || selectedDomainId == null)
                  ? null
                  : _createAlias,
              icon: _aliasSaving
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Symbols.add),
              label: Text('addAlias'.tr()),
            ),
          ),
        ],
        const SizedBox(height: 10),
        if (data.aliases.isEmpty)
          _InlineEmpty(icon: Symbols.alternate_email, message: 'noAliases'.tr())
        else
          for (final alias in data.aliases)
            _AliasRow(alias: alias, onDelete: () => _deleteAlias(alias)),
      ],
    );
  }

  Widget _forwardingBlock(_RoutingData data) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final selectedAliasId =
        data.aliases.any((alias) => alias.id == _aliasId) ? _aliasId : null;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        if (data.aliases.isEmpty)
          Text(
            'workspaceForwardingAliasRequired'.tr(),
            style: text.bodySmall?.copyWith(color: scheme.onSurfaceVariant),
          )
        else ...[
          DropdownButtonFormField<String>(
            initialValue: selectedAliasId,
            isExpanded: true,
            decoration: InputDecoration(
              isDense: true,
              labelText: 'alias'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
            items: [
              for (final alias in data.aliases)
                DropdownMenuItem(value: alias.id, child: Text(alias.address)),
            ],
            onChanged: (value) => setState(() => _aliasId = value),
          ),
          const SizedBox(height: 10),
          TextField(
            controller: _forwardingDestination,
            keyboardType: TextInputType.emailAddress,
            decoration: InputDecoration(
              labelText: 'forwardTo'.tr(),
              hintText: 'forwardToHint'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
          const SizedBox(height: 10),
          Align(
            alignment: Alignment.centerLeft,
            child: FilledButton.tonalIcon(
              onPressed: (_forwardingSaving || selectedAliasId == null)
                  ? null
                  : _createForwarding,
              icon: _forwardingSaving
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Symbols.add),
              label: Text('addForwarding'.tr()),
            ),
          ),
        ],
        const SizedBox(height: 10),
        if (data.forwardings.isEmpty)
          _InlineEmpty(icon: Symbols.forward_to_inbox, message: 'noForwarding'.tr())
        else
          for (final forwarding in data.forwardings)
            _ForwardingRow(
              forwarding: forwarding,
              alias: _aliasById(data.aliases, forwarding.aliasId),
              onDelete: () => _deleteForwarding(forwarding),
            ),
      ],
    );
  }

  Widget _sendUsageBlock(_RoutingData data) => Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [
      _UsageMeter(
        label: 'workspaceDaily'.tr(),
        used: data.sendUsage.daily.used,
        limit: data.sendUsage.daily.limit,
        remaining: data.sendUsage.daily.remaining,
      ),
      const SizedBox(height: 16),
      _UsageMeter(
        label: 'workspaceMonthly'.tr(),
        used: data.sendUsage.monthly.used,
        limit: data.sendUsage.monthly.limit,
        remaining: data.sendUsage.monthly.remaining,
      ),
    ],
  );
}

MailAlias? _aliasById(List<MailAlias> aliases, String id) {
  for (final alias in aliases) {
    if (alias.id == id) return alias;
  }
  return null;
}

class _AliasRow extends StatelessWidget {
  const _AliasRow({required this.alias, required this.onDelete});

  final MailAlias alias;
  final VoidCallback onDelete;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final name = alias.name?.trim();
    return Padding(
      padding: const EdgeInsets.fromLTRB(0, 4, 0, 4),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  alias.address,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: text.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                  ),
                ),
                if (name != null && name.isNotEmpty)
                  Text(
                    name,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: text.bodySmall?.copyWith(
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
              ],
            ),
          ),
          IconButton(
            tooltip: 'removeAlias'.tr(),
            onPressed: onDelete,
            icon: Icon(Symbols.delete_outline, color: scheme.error),
          ),
        ],
      ),
    );
  }
}

class _ForwardingRow extends StatelessWidget {
  const _ForwardingRow({
    required this.forwarding,
    required this.alias,
    required this.onDelete,
  });

  final MailForwarding forwarding;
  final MailAlias? alias;
  final VoidCallback onDelete;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Padding(
      padding: const EdgeInsets.fromLTRB(0, 4, 0, 4),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  forwarding.destination,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: text.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                  ),
                ),
                Text(
                  alias?.address ?? forwarding.aliasId,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: text.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          IconButton(
            tooltip: 'removeForwarding'.tr(),
            onPressed: onDelete,
            icon: Icon(Symbols.delete_outline, color: scheme.error),
          ),
        ],
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Mail dialogs
// ---------------------------------------------------------------------------

class _CreateMailboxSheet extends ConsumerStatefulWidget {
  const _CreateMailboxSheet({required this.mailHost});

  final String mailHost;

  @override
  ConsumerState<_CreateMailboxSheet> createState() =>
      _CreateMailboxSheetState();
}

class _CreateMailboxSheetState extends ConsumerState<_CreateMailboxSheet> {
  final _address = TextEditingController();
  final _name = TextEditingController();
  bool _isDefault = false;

  @override
  void dispose() {
    _address.dispose();
    _name.dispose();
    super.dispose();
  }

  void _submit() {
    final address = _address.text.trim();
    if (address.isEmpty) return;
    final name = _name.text.trim();
    Navigator.pop(
      context,
      (
        address: address,
        name: name.isEmpty ? null : name,
        isDefault: _isDefault,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final helper = widget.mailHost.isEmpty
        ? 'mailboxAddressHelperNoHost'.tr()
        : 'mailboxAddressHelperWithHost'.tr(
            namedArgs: {'host': widget.mailHost},
          );
    return SheetScaffold(
      titleText: 'newMailbox'.tr(),
      heightFactor: 0.6,
      child: ListView(
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 24),
        children: [
          TextField(
            controller: _address,
            autofocus: true,
            keyboardType: TextInputType.emailAddress,
            onChanged: (_) => setState(() {}),
            decoration: InputDecoration(
              labelText: 'mailboxAddress'.tr(),
              helperText: helper,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
          const SizedBox(height: 16),
          TextField(
            controller: _name,
            decoration: InputDecoration(
              labelText: 'mailboxName'.tr(),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
          const SizedBox(height: 8),
          SwitchListTile(
            contentPadding: EdgeInsets.zero,
            title: Text('setAsDefaultMailbox'.tr()),
            value: _isDefault,
            onChanged: (value) => setState(() => _isDefault = value),
          ),
          const SizedBox(height: 16),
          FilledButton.icon(
            onPressed: _address.text.trim().isEmpty ? null : _submit,
            icon: const Icon(Symbols.add, size: 18),
            label: Text('create'.tr()),
          ),
        ],
      ),
    );
  }
}

class _CreateCredentialSheet extends ConsumerStatefulWidget {
  const _CreateCredentialSheet({
    required this.mailboxes,
    required this.mailHost,
  });

  final List<MailMailbox> mailboxes;
  final String mailHost;

  @override
  ConsumerState<_CreateCredentialSheet> createState() =>
      _CreateCredentialSheetState();
}

class _CreateCredentialSheetState
    extends ConsumerState<_CreateCredentialSheet> {
  final _label = TextEditingController();
  final Set<String> _protocols = {'smtp', 'imap'};
  String? _selectedMailboxId;

  @override
  void initState() {
    super.initState();
    _selectedMailboxId = _defaultMailboxId();
  }

  String? _defaultMailboxId() {
    if (widget.mailboxes.isEmpty) return null;
    for (final mailbox in widget.mailboxes) {
      if (mailbox.isDefault) return mailbox.id;
    }
    return widget.mailboxes.first.id;
  }

  @override
  void dispose() {
    _label.dispose();
    super.dispose();
  }

  Future<void> _create() async {
    final label = _label.text.trim();
    if (label.isEmpty) {
      showSnackBar('labelRequired'.tr());
      return;
    }
    final mailboxId = _selectedMailboxId;
    if (mailboxId == null || mailboxId.isEmpty) {
      showSnackBar('mailboxRequired'.tr());
      return;
    }
    try {
      final created = await ref
          .read(wattEngineClientProvider)
          .createMailCredential(
            mailboxId: mailboxId,
            label: label,
            protocols: _protocols.toList(),
          );
      if (!mounted) return;
      Navigator.pop(context, created);
    } catch (error) {
      showSnackBar(wattApiErrorMessage(error));
    }
  }

  @override
  Widget build(BuildContext context) => SheetScaffold(
    titleText: 'createCredential'.tr(),
    heightFactor: 0.7,
    child: ListView(
      padding: const EdgeInsets.fromLTRB(24, 16, 24, 24),
      children: [
        DropdownButtonFormField<String>(
          initialValue: _selectedMailboxId,
          isExpanded: true,
          decoration: InputDecoration(
            isDense: true,
            labelText: 'mailbox'.tr(),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
          items: [
            for (final mailbox in widget.mailboxes)
              DropdownMenuItem(
                value: mailbox.id,
                child: Text(mailbox.fullAddress(widget.mailHost)),
              ),
          ],
          onChanged: (value) => setState(() => _selectedMailboxId = value),
        ),
        const SizedBox(height: 16),
        TextField(
          controller: _label,
          decoration: InputDecoration(
            labelText: 'credentialLabel'.tr(),
            hintText: 'credentialLabelHint'.tr(),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
        const SizedBox(height: 16),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            for (final protocol in const ['smtp', 'imap', 'pop3'])
              FilterChip(
                label: Text(protocol.toUpperCase()),
                selected: _protocols.contains(protocol),
                onSelected: (selected) {
                  setState(() {
                    if (selected) {
                      _protocols.add(protocol);
                    } else {
                      _protocols.remove(protocol);
                    }
                  });
                },
              ),
          ],
        ),
        const SizedBox(height: 24),
        FilledButton.icon(
          onPressed: _protocols.isNotEmpty && _selectedMailboxId != null
              ? _create
              : null,
          icon: const Icon(Symbols.add, size: 18),
          label: Text('createCredential'.tr()),
        ),
      ],
    ),
  );
}

class _CredentialSecretSheet extends StatelessWidget {
  const _CredentialSecretSheet({required this.secret});

  final String secret;

  @override
  Widget build(BuildContext context) {
    final text = Theme.of(context).textTheme;
    return SheetScaffold(
      titleText: 'credentialCreated'.tr(),
      heightFactor: 0.5,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text('saveSecretOnce'.tr()),
            const SizedBox(height: 16),
            SelectableText(
              secret,
              style: text.bodyLarge?.copyWith(
                fontWeight: FontWeight.w600,
                letterSpacing: 0.5,
              ),
            ),
            const Spacer(),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () {
                      Clipboard.setData(ClipboardData(text: secret));
                      showSnackBar('copied'.tr());
                    },
                    icon: const Icon(Symbols.content_copy, size: 18),
                    label: Text('copy'.tr()),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: FilledButton(
                    onPressed: () => Navigator.pop(context),
                    child: Text('done'.tr()),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _CreateDomainSheet extends ConsumerStatefulWidget {
  const _CreateDomainSheet();

  @override
  ConsumerState<_CreateDomainSheet> createState() => _CreateDomainSheetState();
}

class _CreateDomainSheetState extends ConsumerState<_CreateDomainSheet> {
  final _domain = TextEditingController();

  @override
  void dispose() {
    _domain.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final value = _domain.text.trim();
    return SheetScaffold(
      titleText: 'workspaceAddDomain'.tr(),
      heightFactor: 0.45,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextField(
              controller: _domain,
              autofocus: true,
              keyboardType: TextInputType.url,
              onChanged: (_) => setState(() {}),
              decoration: InputDecoration(
                labelText: 'customDomain'.tr(),
                hintText: 'example.com',
                helperText: 'workspaceDomainDnsHint'.tr(),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                ),
              ),
            ),
            const Spacer(),
            FilledButton.icon(
              onPressed: value.isEmpty
                  ? null
                  : () => Navigator.pop(context, value),
              icon: const Icon(Symbols.add, size: 18),
              label: Text('create'.tr()),
            ),
          ],
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Flywheel
// ---------------------------------------------------------------------------

class _FlywheelTab extends ConsumerStatefulWidget {
  const _FlywheelTab({required this.workspace});

  final Workspace workspace;

  @override
  ConsumerState<_FlywheelTab> createState() => _FlywheelTabState();
}

class _FlywheelTabState extends ConsumerState<_FlywheelTab> {
  late Future<List<FlywheelOwnerApp>> _apps;

  @override
  void initState() {
    super.initState();
    _reload();
  }

  void _reload() {
    _apps = ref
        .read(wattEngineClientProvider)
        .listFlywheelApps(widget.workspace.id);
  }

  Future<void> _openApp(FlywheelOwnerApp app) async {
    await showFlywheelApp(
      context,
      workspaceId: widget.workspace.id,
      app: app,
    );
    if (mounted) setState(_reload);
  }

  @override
  Widget build(BuildContext context) => FutureBuilder<List<FlywheelOwnerApp>>(
    future: _apps,
    builder: (context, snapshot) {
      if (snapshot.connectionState != ConnectionState.done) {
        return const PageLoading();
      }
      if (snapshot.hasError) {
        final denied =
            snapshot.error is DioException &&
            (snapshot.error as DioException).response?.statusCode == 403;
        if (denied) {
          return EmptyState(
            icon: Symbols.lock,
            title: 'workspaceFlywheelOwnerOnly'.tr(),
            message: 'workspaceFlywheelOwnerOnlyDescription'.tr(),
          );
        }
        return PageError(
          message: 'workspaceFlywheelLoadError'.tr(),
          onRetry: () => setState(_reload),
        );
      }
      final apps = snapshot.data ?? const <FlywheelOwnerApp>[];
      if (apps.isEmpty) {
        return EmptyState(
          icon: Symbols.sync,
          title: 'workspaceFlywheelEmpty'.tr(),
        );
      }
      return ListView(
        padding: const EdgeInsets.only(top: 16, bottom: 32),
        children: [
          _TitledPanel(
            title: 'flywheel'.tr(),
            child: Column(
              children: [
                for (var i = 0; i < apps.length; i++) ...[
                  if (i > 0) const Divider(height: 1),
                  _FlywheelAppTile(
                    app: apps[i],
                    onTap: () => _openApp(apps[i]),
                  ),
                ],
              ],
            ),
          ),
        ],
      );
    },
  );
}

class _FlywheelAppTile extends StatelessWidget {
  const _FlywheelAppTile({required this.app, required this.onTap});

  final FlywheelOwnerApp app;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(8),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 10),
        child: Row(
          children: [
            const IconBadge(icon: Symbols.sync),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    flywheelAppName(app.appId),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: text.titleSmall?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  const SizedBox(height: 6),
                  Wrap(
                    spacing: 6,
                    runSpacing: 4,
                    children: [
                      StatusChip(
                        label: 'workspaceFlywheelBlobs'.tr(
                          namedArgs: {'count': '${app.blobCount}'},
                        ),
                        icon: Symbols.folder_zip,
                        tone: StatusChipTone.neutral,
                      ),
                      StatusChip(
                        label: 'workspaceFlywheelRevisions'.tr(
                          namedArgs: {
                            'count': '${app.retainedRevisionCountTotal}',
                          },
                        ),
                        icon: Symbols.history,
                        tone: StatusChipTone.neutral,
                      ),
                      StatusChip(
                        label: _formatBytes(app.retainedBytes),
                        icon: Symbols.save,
                        tone: StatusChipTone.neutral,
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Icon(Symbols.chevron_right, color: scheme.onSurfaceVariant),
          ],
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// Shared widgets and helpers
// ---------------------------------------------------------------------------

class _Panel extends StatelessWidget {
  const _Panel({required this.child, this.padding = const EdgeInsets.all(16)});

  final Widget child;
  final EdgeInsetsGeometry padding;

  @override
  Widget build(BuildContext context) => Card.outlined(
    margin: EdgeInsets.zero,
    clipBehavior: Clip.antiAlias,
    child: Padding(padding: padding, child: child),
  );
}

class _TitledPanel extends StatelessWidget {
  const _TitledPanel({required this.title, required this.child, this.trailing});

  final String title;
  final Widget child;
  final Widget? trailing;

  @override
  Widget build(BuildContext context) => Card.outlined(
    margin: EdgeInsets.zero,
    clipBehavior: Clip.antiAlias,
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
          child: Row(
            children: [
              Expanded(
                child: Text(
                  title,
                  style: Theme.of(context).textTheme.titleMedium,
                ),
              ),
              ?trailing,
            ],
          ),
        ),
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 16),
          child: child,
        ),
      ],
    ),
  );
}

class _InlineEmpty extends StatelessWidget {
  const _InlineEmpty({
    required this.message,
    this.description,
    this.icon = Symbols.inbox,
  });

  final String message;
  final String? description;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 12),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: scheme.onSurfaceVariant),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(message, style: text.bodyMedium),
                if (description != null)
                  Text(
                    description!,
                    style: text.bodySmall?.copyWith(
                      color: scheme.onSurfaceVariant,
                    ),
                  ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _InlineError extends StatelessWidget {
  const _InlineError({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        children: [
          Icon(Symbols.error, color: scheme.error),
          const SizedBox(width: 12),
          Expanded(child: Text(message)),
          TextButton(onPressed: onRetry, child: Text('retry'.tr())),
        ],
      ),
    );
  }
}

class _UsageMeter extends StatelessWidget {
  const _UsageMeter({
    required this.label,
    required this.used,
    required this.limit,
    this.remaining,
    this.isBytes = false,
  });

  final String label;
  final int used;
  final int limit;
  final int? remaining;
  final bool isBytes;

  String _format(int value) => isBytes ? _formatBytes(value) : '$value';

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final hasLimit = limit > 0;
    final ratio = hasLimit ? (used / limit).clamp(0.0, 1.0) : 0.0;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Expanded(
              child: Text(
                label,
                style: text.titleSmall?.copyWith(fontWeight: FontWeight.w600),
              ),
            ),
            const SizedBox(width: 12),
            Text(
              hasLimit ? '${_format(used)} / ${_format(limit)}' : _format(used),
              style: text.bodyMedium?.copyWith(fontWeight: FontWeight.w600),
            ),
          ],
        ),
        if (hasLimit) ...[
          const SizedBox(height: 8),
          ClipRRect(
            borderRadius: BorderRadius.circular(6),
            child: LinearProgressIndicator(value: ratio, minHeight: 8),
          ),
        ],
        if (remaining != null) ...[
          const SizedBox(height: 6),
          Text(
            '${'quotaRemaining'.tr()}: '
            '${hasLimit ? _format(remaining!) : 'mailStorageQuotaUnlimited'.tr()}',
            style: text.bodySmall?.copyWith(color: scheme.onSurfaceVariant),
          ),
        ],
      ],
    );
  }
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

/// Human-readable byte size, matching the app's Drive usage wording.
String _formatBytes(int bytes) {
  if (bytes < 1024) return '$bytes B';
  if (bytes < 1024 * 1024) return '${(bytes / 1024).toStringAsFixed(1)} KB';
  if (bytes < 1024 * 1024 * 1024) {
    return '${(bytes / (1024 * 1024)).toStringAsFixed(1)} MB';
  }
  return '${(bytes / (1024 * 1024 * 1024)).toStringAsFixed(2)} GB';
}

String _formatDate(DateTime value) {
  final local = value.toLocal();
  return '${local.year.toString().padLeft(4, '0')}-'
      '${local.month.toString().padLeft(2, '0')}-'
      '${local.day.toString().padLeft(2, '0')}';
}

String _formatDateTime(DateTime value) {
  final local = value.toLocal();
  return '${_formatDate(local)} '
      '${local.hour.toString().padLeft(2, '0')}:'
      '${local.minute.toString().padLeft(2, '0')}';
}

Workspace? _workspaceBySlug(List<Workspace> items, String slug) {
  for (final workspace in items) {
    if (workspace.slug == slug) return workspace;
  }
  return null;
}

/// Workspace member roles, mirroring the members sheet's labels.
String _roleName(int role) => switch (role) {
  25 => 'viewer'.tr(),
  50 => 'memberRole'.tr(),
  75 => 'admin'.tr(),
  100 => 'owner'.tr(),
  _ => 'role'.tr(args: [role.toString()]),
};
